/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109741-gbbe95f7353-20230201"
#endif /* AVUTIL_FFVERSION_H */
